# Generated by Django 3.1.2 on 2020-11-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='SubType',
            new_name='subType',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='SubType',
            new_name='subType',
        ),
    ]
