# Generated by Django 3.1.2 on 2020-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0004_subtype_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
