# Generated by Django 3.1.2 on 2020-11-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0007_transations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transations',
            name='paytmOID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
