# Generated by Django 3.1.2 on 2020-11-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0008_transations_paytmoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transations',
            name='subType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubsApp.subtype'),
        ),
    ]
