# Generated by Django 3.1.2 on 2020-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0009_transations_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
