# Generated by Django 3.1.2 on 2021-02-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubsApp', '0011_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubsApp.subtype'),
        ),
    ]
